#!/usr/bin/env python3
"""Run every search of the A* report and write its figures, tables and results.

Each number in the report's results comes out of this script, so what the
figures show is what the algorithms do.  Outputs, all in output/:

  map_graph.tex        the 64-district graph, Dhaka and Sylhet marked
  map_panels.tex       three panels: what each search expanded, and its route
  map_astar_rows.tex   table rows: the districts A* expanded, with g, h, f
  bddata.tex           g and h of all 64 districts, for the 3D map figures
  grid_orders.tex      expansion order and route of each search on the grid
  story_iso_*.tex      the eight-city example in an isometric view
  trace_original.tex   table rows: A* trace with the admissible estimate
  trace_manhattan.tex  table rows: A* trace with the Manhattan estimate
  trace_dijkstra.tex   table rows: Dijkstra trace on the eight-city graph
  trace_greedy.tex     table rows: greedy best-first trace on the eight-city graph
  counterexample.tex   the admissible but inconsistent example
  results.txt          a plain-text summary of every run

The .tex files go to output/tex/ and are the figure sources used by the report.

Run:  python3 make_figures.py      (needs only the Python standard library)
"""
import json
import math
import os

from searches import search, undirected, exact_to_goal, haversine_km

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'output')
FIG = os.path.join(OUT, 'tex')
os.makedirs(FIG, exist_ok=True)
summary = []


def write(name, lines):
    with open(os.path.join(FIG, name), 'w', encoding='utf-8') as f:
        f.write('% generated by make_figures.py -- do not edit by hand\n')
        f.write('\n'.join(lines) + '\n')


def num(x, digits=1):
    return f'{x:.{digits}f}'


# ======================================================================
#  1. the district map
# ======================================================================
data = json.load(open(os.path.join(HERE, 'data', 'bangladesh.json')))
coast = data['coast']
co = {k: tuple(v) for k, v in data['districts'].items()}
edges = [(a, b, haversine_km(co[a], co[b])) for a, b in data['edges']]
madj = undirected(edges)
START, GOAL = 'dhaka', 'sylhet'
hmap = lambda v: haversine_km(co[v], co[GOAL])
NAMES = {'coxsbazar': "Cox's Bazar", 'chapainawabganj': 'Chapainawabganj'}
pretty = lambda n: NAMES.get(n, n.capitalize())

runs = {m: search(madj, START, GOAL, hmap, m, trace=(m == 'astar'))
        for m in ('dijkstra', 'greedy', 'astar')}
exact = exact_to_goal(madj, GOAL)
admissible = all(hmap(v) <= exact[v] + 1e-9 for v in co)
consistent = all(hmap(a) <= w + hmap(b) + 1e-9 for a in madj for b, w in madj[a])
summary.append(f'map: {len(co)} districts, {len(edges)} edges, '
               f'straight-line h admissible={admissible} consistent={consistent}')
for m, r in runs.items():
    summary.append(f'  {m:8s} expanded {len(r["order"]):2d}  cost {num(r["cost"])} km  '
                   f'path {" > ".join(map(pretty, r["path"]))}')
summary.append(f'  h(Dhaka) = {num(hmap(START))} km, exact remaining = {num(exact[START])} km')

LON0, LAT0 = 88.0, 20.7


def xy(p):
    return f'({num(p[0] - LON0, 3)},{num(p[1] - LAT0, 3)})'


def map_base(scale):
    """Border, edges and district dots, drawn at `scale` cm per degree."""
    L = [f'\\begin{{tikzpicture}}[x={num(0.92 * scale, 3)}cm, y={num(scale, 3)}cm]']
    L.append('  \\fill[maplandfill] ' + ' -- '.join(xy(p) for p in coast) + ' -- cycle;')
    L.append('  \\draw[mapborder] ' + ' -- '.join(xy(p) for p in coast) + ' -- cycle;')
    for n, p in co.items():
        L.append(f'  \\coordinate ({n}) at {xy(p)};')
    L.append('  \\foreach \\a/\\b in {' +
             ', '.join(f'{a}/{b}' for a, b, _ in edges) + '}')
    L.append('    {\\draw[mapedge] (\\a) -- (\\b);}')
    L.append('  \\foreach \\n in {' + ', '.join(co) + '}')
    L.append('    {\\node[mapdot] at (\\n) {};}')
    return L


def map_ends(L, labels=True):
    L.append(f'  \\node[mapstart] at ({START}) {{}};')
    L.append(f'  \\node[mapgoal] at ({GOAL}) {{}};')
    if labels:
        L.append(f'  \\node[maplabel, anchor=north east] at ({START}) {{Dhaka}};')
        L.append(f'  \\node[maplabel, anchor=south west] at ({GOAL}) {{Sylhet}};')


# full map, for Section 2
L = map_base(1.55)
map_ends(L)
L.append('\\end{tikzpicture}')
write('map_graph.tex', L)

# three panels, for Section 5
COLOR = {'dijkstra': 'algdijkstra', 'greedy': 'alggreedy', 'astar': 'algastar'}
TITLE = {'dijkstra': "Dijkstra's algorithm", 'greedy': 'Greedy best-first search',
         'astar': 'A* search'}
L = []
for k, m in enumerate(('dijkstra', 'greedy', 'astar')):
    r = runs[m]
    L.append(f'\\begin{{subfigure}}[t]{{0.32\\textwidth}}\\centering')
    L += ['  ' + s for s in map_base(0.78)]
    L.append('    \\foreach \\n in {' + ', '.join(r['order']) + '}')
    L.append(f'      {{\\node[mapdot, fill={COLOR[m]}!55, draw={COLOR[m]}] at (\\n) {{}};}}')
    L.append(f'    \\draw[maproute, draw={COLOR[m]}] ' +
             ' -- '.join(f'({n})' for n in r['path']) + ';')
    map_ends(L, labels=False)
    L.append('  \\end{tikzpicture}')
    L.append(f'  \\caption{{{TITLE[m]}: {len(r["order"])} districts expanded, '
             f'route {num(r["cost"])}\\,km.}}')
    L.append(f'  \\label{{fig:map-{m}}}')
    L.append('\\end{subfigure}' + ('\\hfill' if k < 2 else ''))
write('map_panels.tex', L)

# A* on the map, as table rows
L = []
for i, u in enumerate(runs['astar']['order'], 1):
    g = runs['astar']['g'][u]
    L.append(f'{i} & {pretty(u)} & {num(g)} & {num(hmap(u))} & {num(g + hmap(u))} \\\\')
write('map_astar_rows.tex', L)

# ======================================================================
#  2. the 16 x 10 grid with a U-shaped wall
# ======================================================================
W, H = 16, 10
GS, GG = (1, 4), (14, 6)
walls = ({(12, r) for r in range(3, 8)} | {(c, 3) for c in range(4, 13)}
         | {(c, 7) for c in range(4, 13)})
free = {(c, r) for c in range(W) for r in range(H)} - walls
gadj = {v: [((v[0] + dc, v[1] + dr), 1) for dc, dr in ((1, 0), (-1, 0), (0, 1), (0, -1))
            if (v[0] + dc, v[1] + dr) in free] for v in free}
manh = lambda v: abs(v[0] - GG[0]) + abs(v[1] - GG[1])
gruns = {m: search(gadj, GS, GG, manh, m) for m in ('dijkstra', 'greedy', 'astar')}
summary.append(f'grid: {W} x {H}, {len(walls)} wall cells, 4-connected, unit cost, '
               f'Manhattan h')
for m, r in gruns.items():
    frontier = set(r['g']) - set(r['order'])
    summary.append(f'  {m:8s} expanded {len(r["order"]):3d}  frontier {len(frontier):3d}  '
                   f'cost {int(r["cost"])}')


# ======================================================================
#  3. the eight-city running example
# ======================================================================
SE = [('D', 'N', 2), ('D', 'B', 5), ('N', 'B', 1), ('B', 'H', 2), ('H', 'S', 3),
      ('D', 'G', 1), ('N', 'K', 3), ('K', 'H', 4), ('B', 'C', 3), ('C', 'S', 10)]
sadj = undirected(SE)
H_ORIG = dict(D=7, N=5, B=4, H=2, S=0, G=8, K=4, C=7)
GRIDPOS = dict(D=(0, 4), N=(4, 6), B=(8, 4), H=(12, 6), S=(16, 4), G=(2, 1), K=(8, 8), C=(13, 1))
H_MANH = {v: abs(x - GRIDPOS['S'][0]) + abs(y - GRIDPOS['S'][1]) for v, (x, y) in GRIDPOS.items()}
sexact = exact_to_goal(sadj, 'S')
CITY = dict(D='Dhaka', N='Narsingdi', B='Brahmanbaria', H='Habiganj', S='Sylhet',
            G='Gazipur', K='Kishoreganj', C='Cumilla')
def trace_rows(r, keyfn, keycell, updcell):
    """Table rows of a traced run.  The queue of each step is listed in the
    order in which the search would extract it: by key, ties first in, first
    out (the order in which the vertices were last inserted)."""
    stamp = {'D': (0, 0)}
    L = []
    for i, st in enumerate(r['steps'], 1):
        opn = sorted(st['open'].items(), key=lambda kv: (keyfn(kv[0], kv[1]), stamp[kv[0]]))
        cells = ', '.join(f'\\cty{{{v}}}:~{int(keyfn(v, val))}' for v, val in opn)
        u = st['extract']
        L.append(f'{i} & {cells} & \\cty{{{u}}} & {keycell(u, st["open"][u])} & '
                 f'{updcell(st["updates"]) if u != "S" else "destination reached"} \\\\')
        for j, (v, _) in enumerate(st['updates']):
            stamp[v] = (i, j)
    return L


for name, hh in (('original', H_ORIG), ('manhattan', H_MANH)):
    adm = all(hh[v] <= sexact[v] for v in hh)
    con = all(hh[a] <= w + hh[b] for a in sadj for b, w in sadj[a])
    r = search(sadj, 'D', 'S', hh.get, 'astar', trace=True)
    summary.append(f'eight cities, {name} h: admissible={adm} consistent={con}  '
                   f'expanded {"".join(r["order"])}  path {"".join(r["path"])}  cost {int(r["cost"])}')
    write(f'trace_{name}.tex', trace_rows(
        r, lambda v, val: val[2],
        lambda u, val: f'${int(val[0])}+{int(val[1])}={int(val[2])}$',
        lambda up: ', '.join(f'$g(\\cty{{{v}}})={int(gv)}$' for v, gv in up) or 'none'))

# Dijkstra's algorithm and greedy best-first search on the same graph
r = search(sadj, 'D', 'S', H_ORIG.get, 'dijkstra', trace=True)
summary.append(f'eight cities, dijkstra: expanded {"".join(r["order"])}  '
               f'path {"".join(r["path"])}  cost {int(r["cost"])}')
write('trace_dijkstra.tex', trace_rows(
    r, lambda v, val: val[0],
    lambda u, val: f'${int(val[0])}$',
    lambda up: ', '.join(f'$g(\\cty{{{v}}})={int(gv)}$' for v, gv in up) or 'none'))
r = search(sadj, 'D', 'S', H_ORIG.get, 'greedy', trace=True)
summary.append(f'eight cities, greedy: expanded {"".join(r["order"])}  '
               f'path {"".join(r["path"])}  cost {int(r["cost"])}')
write('trace_greedy.tex', trace_rows(
    r, lambda v, val: val[1],
    lambda u, val: f'${int(val[1])}$',
    lambda up: ', '.join(f'\\cty{{{v}}}' for v, _ in up) or 'none'))
summary.append('  exact remaining cost h*: ' +
               ', '.join(f'{v}={int(sexact[v])}' for v in 'DNBHSGKC'))


# ======================================================================
#  4. admissible but inconsistent: the closed set loses the optimum
# ======================================================================
CE = [('s', 'a', 1), ('a', 'c', 1), ('s', 'b', 1), ('b', 'c', 2), ('c', 't', 3)]
cadj = undirected(CE)
H_CE = dict(s=0, a=4, b=1, c=1, t=0)
cexact = exact_to_goal(cadj, 't')
r1 = search(cadj, 's', 't', H_CE.get, 'astar')
r2 = search(cadj, 's', 't', H_CE.get, 'reopen')
summary.append(f'counterexample: admissible={all(H_CE[v] <= cexact[v] for v in H_CE)} '
               f'consistent={all(H_CE[a] <= w + H_CE[b] for a in cadj for b, w in cadj[a])}')
summary.append(f'  closed set: order {"".join(r1["order"])} path {"".join(r1["path"])} cost {int(r1["cost"])}')
summary.append(f'  reopening:  order {"".join(r2["order"])} path {"".join(r2["path"])} cost {int(r2["cost"])}')
CPOS = dict(s=(0, 0), a=(1.8, 1.0), b=(1.8, -1.0), c=(3.6, 0), t=(5.4, 0))
L = ['\\begin{tikzpicture}[x=1.35cm, y=1.1cm]']
for v, (x, y) in CPOS.items():
    L.append(f'  \\coordinate ({v}) at ({x},{y});')
for a, b, w in CE:
    L.append(f'  \\draw[storyedge] ({a}) -- node[storyweight] {{{w}}} ({b});')
for v in CPOS:
    style = 'storystart' if v == 's' else ('storygoal' if v == 't' else 'storynode')
    side = 'above' if CPOS[v][1] >= 0 else 'below'
    L.append(f'  \\node[{style}] at ({v}) {{${v}$}};')
    L.append(f'  \\node[storyh, {side}=11pt] at ({v}) {{$h={H_CE[v]}$}};')
L.append('\\end{tikzpicture}')
write('counterexample.tex', L)

# ======================================================================
#  5. data for the 3D figures (read by figures3d/*.tex)
# ======================================================================
# every district: g = Dijkstra distance from Dhaka, h = straight line to Sylhet
gfull = search(madj, START, None, lambda v: 0, 'dijkstra')['g']
L = ['\\newcommand{\\bddata}{%']
items = [f'{n}/{num(gfull[n])}/{num(hmap(n))}' for n in sorted(co)]
for k in range(0, len(items), 3):
    L.append('  ' + ', '.join(items[k:k + 3]) + (',' if k + 3 < len(items) else '}'))
# the districts each algorithm expanded, in order
for m, key in (('dijkstra', 'bddj'), ('greedy', 'bdgr'), ('astar', 'bdas')):
    L.append(f'\\newcommand{{\\{key}order}}{{{", ".join(runs[m]["order"])}}}')
    L.append(f'\\newcommand{{\\{key}route}}{{{" -- ".join(f"({n})" for n in runs[m]["path"])}}}')
write('bddata.tex', L)

# grid expansion orders and routes, for the 3D grid panels
L = []
for m, key in (('dijkstra', 'dj'), ('greedy', 'gr'), ('astar', 'as')):
    r = gruns[m]
    L.append(f'\\newcommand{{\\{key}order}}{{%')
    cells = [f'{c}/{rr}' for c, rr in r['order']]
    for k in range(0, len(cells), 14):
        L.append('  ' + ', '.join(cells[k:k + 14]) + (',' if k + 14 < len(cells) else '}'))
    L.append(f'\\newcommand{{\\{key}route}}{{' +
             ' -- '.join(f'({c + 0.5},{rr + 0.5})' for c, rr in r['path']) + '}')
write('grid_orders.tex', L)

# ======================================================================
#  6. the eight-city graph seen from above at an angle (isometric)
# ======================================================================
def iso(x, y):
    """An affine isometric camera, in cm."""
    return (0.39 * x + 0.10 * y) * 1.08, (-0.065 * x + 0.29 * y) * 1.08


def iso_view(closed, route, color, hvals, grid):
    pts = {v: iso(*GRIDPOS[v]) for v in GRIDPOS}
    L = ['\\begin{tikzpicture}[x=1cm, y=1cm]']
    plate = [iso(-1, -1), iso(17, -1), iso(17, 9), iso(-1, 9)]
    sh = ' -- '.join(f'({num(x, 3)},{num(y - 0.15, 3)})' for x, y in plate)
    L.append(f'  \\fill[black!10] {sh} -- cycle;')
    L.append('  \\draw[draw=rblue!14, fill=rbluelt!35, line width=0.6pt] ' +
             ' -- '.join(f'({num(x, 3)},{num(y, 3)})' for x, y in plate) + ' -- cycle;')
    if grid:
        for gx in range(0, 17):
            (x1, y1), (x2, y2) = iso(gx, 0), iso(gx, 8)
            L.append(f'  \\draw[black!{19 if gx % 4 == 0 else 10}, line width=0.3pt] '
                     f'({num(x1, 3)},{num(y1, 3)}) -- ({num(x2, 3)},{num(y2, 3)});')
        for gy in range(0, 9):
            (x1, y1), (x2, y2) = iso(0, gy), iso(16, gy)
            L.append(f'  \\draw[black!{19 if gy % 4 == 0 else 10}, line width=0.3pt] '
                     f'({num(x1, 3)},{num(y1, 3)}) -- ({num(x2, 3)},{num(y2, 3)});')
    for v, (x, y) in pts.items():
        L.append(f'  \\coordinate ({v}) at ({num(x, 3)},{num(y, 3)});')
    onroute = set(zip(route, route[1:])) | set(zip(route[1:], route))
    for a, b, w in SE:
        style = f'draw={color}, line width=2pt' if (a, b) in onroute else 'draw=rblue!55, line width=1pt'
        L.append(f'  \\draw[{style}] ({a}) -- ({b});')
    for a, b, w in SE:
        L.append(f'  \\node[isoweight] at ($({a})!0.5!({b})$) {{{w}}};')
    for v in GRIDPOS:
        if v in route:
            fill, stroke = f'{color}!15', color
        elif v in closed:
            fill, stroke = 'gray!30', 'gray'
        else:
            fill, stroke = 'white', 'rblue!70'
        if v == 'D':
            stroke = 'algastar'
        if v == 'S':
            stroke = 'cbRed'
        L.append(f'  \\isodisc{{{v}}}{{{fill}}}{{{stroke}}}{{{v}}}{{{hvals[v]}}}')
    L.append('\\end{tikzpicture}')
    return L


r_o = search(sadj, 'D', 'S', H_ORIG.get, 'astar')
r_m = search(sadj, 'D', 'S', H_MANH.get, 'astar')
write('story_iso_original.tex', iso_view(set(r_o['order']), r_o['path'], 'algastar', H_ORIG, False))
write('story_iso_manhattan.tex', iso_view(set(r_m['order']), r_m['path'], 'alggreedy', H_MANH, True))
r_d = search(sadj, 'D', 'S', H_ORIG.get, 'dijkstra')
r_g = search(sadj, 'D', 'S', H_ORIG.get, 'greedy')
write('story_iso_plain.tex', iso_view(set(), [], 'algastar', H_ORIG, False))
write('story_iso_dijkstra.tex', iso_view(set(r_d['order']), r_d['path'], 'algdijkstra', H_ORIG, False))
write('story_iso_greedy.tex', iso_view(set(r_g['order']), r_g['path'], 'alggreedy', H_ORIG, False))

# ======================================================================
#  7. the game map of the applications figure: check its two route costs
# ======================================================================
GW, GH = 11, 7
water = {(c, r) for c in (5, 6) for r in range(GH)} - {(5, 5), (6, 5)}   # bridge on row 5
mud = {(7, 3), (8, 3), (7, 4), (8, 4)}
blocked = {(3, 3), (2, 3), (2, 2), (1, 6), (10, 4), (4, 4), (8, 2), (8, 0), (3, 0)}
tiles = {(c, r) for c in range(GW) for r in range(GH)} - blocked
cost = lambda v: 5 if v in water else (3 if v in mud else 1)
tadj = {v: [((v[0] + dc, v[1] + dr), cost((v[0] + dc, v[1] + dr)))
            for dc, dr in ((1, 0), (-1, 0), (0, 1), (0, -1)) if (v[0] + dc, v[1] + dr) in tiles]
        for v in tiles}
rg = search(tadj, (0, 1), (10, 2), lambda v: 0, 'dijkstra')
straight = [(c, 1) for c in range(11)] + [(10, 2)]
summary.append(f'game map: cheapest route {len(rg["path"]) - 1} steps, cost {int(rg["cost"])}; '
               f'straight route {len(straight) - 1} steps, cost {sum(cost(v) for v in straight[1:])}')

with open(os.path.join(OUT, 'results.txt'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(summary) + '\n')
print('\n'.join(summary))
